### ISSUE TITLE
Error: getaddrinfo ENOTFOUND tinyurl.com

### ISSUE THREAD

**Issue by balladav** [danielyaa5/puml-for-markdown#5]
After generating an empty .gitignore file in order to skip the first issue already under investigation, I got this
FATAL EXCEPTION
Error: getaddrinfo ENOTFOUND tinyurl.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'tinyurl.com'
}

for  puml-for-markdown -t in the puml-for-markdown folder:
Processing md file at C:/Users/xxxxx/AppData/Roaming/npm/node_modules/puml-for-markdown/CONTRIBUTING.md
Processing md file at C:/Users/xxxxx/AppData/Roaming/npm/node_modules/puml-for-markdown/LICENSE.md
...
FATAL EXCEPTION
Error: Could not find puml for md link path = ./puml/level_1_system_view.puml, absolute path = C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\puml\level_1_system_view.puml
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:171:23
    at String.replace (<anonymous>)
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:167:20
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:38:16
    at Array.map (<anonymous>)
    at replaceIgnore (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:36:45)
    at replaceMdIgnoringInlineCode (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:44:12)
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:52:57
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:38:16
    at Array.map (<anonymous>)
    at replaceIgnore (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:36:45)
    at replaceMdIgnoringCodeBlocks (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:48:12)
    at replaceMdIgnoringCode (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:52:12)
    at processMdFile (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:166:36)
    at runOnce (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\puml-for-markdown\index.js:216:34)

**Comment by danielyaa5** [comment]
Merging this with issue https://github.com/danielyaa5/puml-for-markdown/issues/6
